name              'chefdk-fundamentals'
maintainer        'Chef Software, Inc.'
maintainer_email  'training@chef.io'
license           'Proprietary - All Rights Reserved'
description       'ChefDK Fundamentals Workshop: Full content repository'
version           '3.0.0-alpha'
